name: counter_app
description: "Counter App using Material 3"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Material Icons and Cupertino optional
  cupertino_icons: ^1.0.8

  # Animations helpers (optional but kept minimal)
  # No extra packages required for basic AnimatedSwitcher

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon.png"
  min_sdk_android: 21
